[meta
  title:"idyll-loader-component"
  description:"A loader for idyll so your scripts don't block" /]

[Header
  title:"idyll-loader-component"
  author:"Ricky Reusser"
  authorLink:"https://twitter.com/rickyreusser" /]

This document uses [Link href:"https://github.com/idyll-lang/idyll-loader-component" text:"idyll-loader-component"/] to build a component that displays plots using an external library without blocking the entire page.

[Loader]
This paragraph is wrapped in `Loader` so that it shows up only on scroll (which is probably right away if you're at the top of the page when loading).
[/Loader]

[Loader error:"This is a component with an externally supplied error message"]
This text is never displayed
[/Loader]

[Aside]
  [Lineplot style:`{height: '300px'}`/]
[/Aside]

Moving on to the plots, this is a plot of [Equation]y = x[/Equation]:

It's accomplished by creating [link href:"https://github.com/rreusser/idyll-loader-component/blob/master/examples/basic/components/lineplot.js" text:"a custom component"/] that render this plot:

```
class Lineplot extends PlotlyComponent {
  plot (gd) {
    Plotly.plot(gd, {
      data: [{
        y: [1, 2, 3]
      }],
      layout: {
        margin: {t: 40, r: 30, b: 30, l: 30}
      }
    });
  }
}
```

The plotly component just uses the loader, which is also very simple to use:

```
render () {
  return <Loader src="..." onLoad={this.onLoad}>
    I'm content added after the script loads!
  </Loader>
}
```

[Aside]
  [Lineplot style:`{height: '300px'}`/]
[/Aside]

And for some reason it's the same plot again, but hey at least it only loads the plotly cdn script once and the end-user doesn't have to worry about including the script at all.

And of course it wouldn't be complete without good old json loading:

[Plotly src:"data/99.json" style:`{height:'500px'}`/]
